import type { Metadata } from 'next'
import localFont from 'next/font/local'

import AmplitudeInitializer from '@components/amplitude-initializer/AmplitudeInitializer'
import AuthInterceptor from '@components/auth-interceptor/AuthInterceptor'
import { Providers } from '@components/providers/Providers'
import TokenRefresher from '@components/tokenRefresher/TokenRefresher'

import './globals.scss'

export const metadata: Metadata = {
  title: 'WriteOn - AI 집필 플랫폼',
  description: 'Generated by create next app',
}

// NOTE(hajae): Next.js 폰트 자동 최적화
const pretendard = localFont({
  src: './styles/fonts/PretendardVariable.woff2',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body>
        <AmplitudeInitializer />
        <Providers>
          <TokenRefresher>
            <AuthInterceptor>
              <div id="modal"></div>
              {children}
            </AuthInterceptor>
          </TokenRefresher>
        </Providers>
      </body>
    </html>
  )
}
