import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Script from 'next/script'

import AmplitudeInitializer from '@components/amplitude-initializer/AmplitudeInitializer'
import AuthInterceptor from '@components/auth-interceptor/AuthInterceptor'
import { Providers } from '@components/providers/Providers'
import TokenRefresher from '@components/tokenRefresher/TokenRefresher'

import './globals.scss'

export const metadata: Metadata = {
  title: 'WriteOn - AI 집필 플랫폼',
  description: 'Generated by create next app',
}

// NOTE(hajae): Next.js 폰트 자동 최적화
const pretendard = localFont({
  src: './styles/fonts/PretendardVariable.woff2',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const markerProjectId = process.env.MARKER_PROJECT_ID

  return (
    <html lang="ko" className={pretendard.className}>
      <body>
        <AmplitudeInitializer />
        <Providers>
          <TokenRefresher>
            <AuthInterceptor>
              <div id="modal"></div>
              {children}
            </AuthInterceptor>
          </TokenRefresher>
        </Providers>

        <Script id="marker-io" strategy="afterInteractive">
          {`
            window.markerConfig = {
              project: '${markerProjectId}',
              source: 'snippet'
            };

            !function(e,r,a){
              if(!e.__Marker){
                e.__Marker={};
                var t=[],n={__cs:t};
                ["show","hide","isVisible","capture","cancelCapture","unload","reload","isExtensionInstalled","setReporter","clearReporter","setCustomData","on","off"]
                .forEach(function(e){
                  n[e]=function(){
                    var r=Array.prototype.slice.call(arguments);
                    r.unshift(e),t.push(r)
                  }
                }),
                e.Marker=n;
                var s=r.createElement("script");
                s.async=1;
                s.src="https://edge.marker.io/latest/shim.js";
                var i=r.getElementsByTagName("script")[0];
                i.parentNode.insertBefore(s,i)
              }
            }(window,document);
          `}
        </Script>
      </body>
    </html>
  )
}
