import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { ToastProvider } from '@components/toast/ToastProvider'

import './globals.scss'

export const metadata: Metadata = {
  title: 'MODI For commit',
  description: 'Generated by create next app',
}

// NOTE(hajae): Next.js 폰트 자동 최적화
const pretendard = localFont({
  src: './styles/fonts/PretendardVariable.woff2',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body>
        <ToastProvider>
          <div id="modal"></div>
          {children}
        </ToastProvider>
      </body>
    </html>
  )
}
