export const TOAST_MESSAGE = Object.freeze({
  SIGN_UP_COMPLETE: '회원가입 완료. 이메일을 확인하고 계정을 활성화해 주세요',
  NETWORK_ERROR: '현재 서버와의 연결이 원활하지 않습니다. 잠시 후 다시 시도해 주세요',
  SESSION_DONE: '세션이 만료되었습니다. 다시 로그인해주세요.',
  LIMIT_PRODUCT_COUNT: '최대 30개의 작품만 집필할 수 있어요',
  SUCCESS_SAVE_PRODUCT: '저장이 완료되었습니다.',
  FAIL_SAVE_PRODUCT: '저장을 실패했습니다. 다시 시도해주세요.',
  FIND_PASSWORD_COMPLETE: '이메일을 전송했어요.',
  CHANGE_PASSWORD_COMPLETE: '비밀번호 변경이 완료되었어요.',
  LOGIN_FAIL: '이메일 또는 비밀번호가 잘못되었거나 존재하지 않습니다.',
  ACCOUNT_ACTIVATION_SUCCESS: '계정이 활성화 되었어요. 로그인 해주세요',
  UNKNOWN_ERROR: '알 수 없는 오류가 발생했어요.',
  FAIL_SUBMIT_FEEDBACK: '이미 평가되었어요.',
  SUCCESS_SUBMIT_FEEDBACK: '응답 평가가 성공적으로 완료되었습니다.',
})
