#!/bin/sh

# 커밋 메시지를 읽어옴
commit_message_file="$1"
commit_message=$(cat "$commit_message_file")

# 브랜치 이름에서 원하는 부분 추출
branch_name=$(git symbolic-ref --short HEAD)
ticket_number=$(echo "$branch_name" | cut -d '_' -f 1)

# 커밋 메시지에 추출한 부분 추가
new_commit_message="$ticket_number $commit_message"

# 수정된 커밋 메시지를 저장
echo "$new_commit_message" > "$commit_message_file"

npx --no-install commitlint --edit "$commit_message_file"